--- 
- !ruby/object:Piece 
  board_label: Q
  image_src: queen_w.gif
  current_position: d1
  cname: Queen
  player_owner: "1"
- !ruby/object:Piece 
  board_label: K
  image_src: king_w.gif
  current_position: e1
  cname: King
  player_owner: "1"
- !ruby/object:Piece 
  board_label: b
  image_src: bishop_w.gif
  current_position: c1
  cname: bishop
  player_owner: "1"
- !ruby/object:Piece 
  board_label: b
  image_src: bishop_w.gif
  current_position: f1
  cname: bishop
  player_owner: "1"
- !ruby/object:Piece 
  board_label: N
  image_src: knight_w.gif
  current_position: b1
  cname: knight
  player_owner: "1"
- !ruby/object:Piece 
  board_label: N
  image_src: knight_w.gif
  current_position: g1
  cname: knight
  player_owner: "1"
- !ruby/object:Piece 
  board_label: R
  image_src: rook_w.gif
  current_position: a1
  cname: rook
  player_owner: "1"
- !ruby/object:Piece 
  board_label: R
  image_src: rook_w.gif
  current_position: h1
  cname: rook
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: a2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: b2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: c2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: d2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: e2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: f2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: g2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_w.gif
  current_position: h2
  cname: pawn
  player_owner: "1"
- !ruby/object:Piece 
  board_label: Q
  image_src: queen_b.gif
  current_position: d8
  cname: Queen
  player_owner: "2"
- !ruby/object:Piece 
  board_label: K
  image_src: king_b.gif
  current_position: e8
  cname: King
  player_owner: "2"
- !ruby/object:Piece 
  board_label: b
  image_src: bishop_b.gif
  current_position: c8
  cname: bishop
  player_owner: "2"
- !ruby/object:Piece 
  board_label: b
  image_src: bishop_b.gif
  current_position: f8
  cname: bishop
  player_owner: "2"
- !ruby/object:Piece 
  board_label: N
  image_src: knight_b.gif
  current_position: b8
  cname: knight
  player_owner: "2"
- !ruby/object:Piece 
  board_label: N
  current_position: g8
  image_src: knight_b.gif
  cname: knight
  player_owner: "2"
- !ruby/object:Piece 
  board_label: R
  image_src: rook_b.gif
  current_position: a8
  cname: rook
  player_owner: "2"
- !ruby/object:Piece 
  board_label: R
  image_src: rook_b.gif
  current_position: h8
  cname: rook
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: a7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: b7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: c7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: d7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: e7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: f7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: g7
  cname: pawn
  player_owner: "2"
- !ruby/object:Piece 
  board_label: i
  image_src: pawn_b.gif
  current_position: h7
  cname: pawn
  player_owner: "2"
