# SQL Server

development: &DEV
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  #use either sqllite section or mysql 
  adapter: sqlite3
  database: db/test.sqlite3  # or try ":memory:" for speed
  pool: 5
  timeout: 5000
  #verbosity: quiet
  
cucumber:
  <<: *TEST

profiling:
  <<: *DEV