# SQL Server

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  #use either sqllite section or mysql 
  adapter: sqlite3
  database: db/test.sqlite3  # or try ":memory:" for speed
  pool: 5
  timeout: 5000
  #verbosity: quiet
  
  #adapter: mysql
  #host: localhost
  #database: chessonrails_test
  #username: chessonrails
  #password: ch3550nrails
