# SQL Server

development:
  adapter: sqlite3
  database: db/development.sqlite3

  # adapter: mysql
  # host: localhost
  # database: chessonrails_development
  # username: chessonrails
  # assword: ch3550nrails

test:
  # use either sqllite section or mysql 
  # database: ":memory:" once worked (sigh..)
  database: db/test.sqlite3
  adapter: sqlite3
  verbosity: quiet
  
  # adapter: mysql
  # host: localhost
  # database: chessonrails_test
  # username: chessonrails
  # password: ch3550nrails
