development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  # database: ":memory:" may work ?
  database: db/test.sqlite3
  adapter: sqlite3
  verbosity: quiet
  
cucumber:
  database: db/cucumber.sqlite3
  adapter: sqlite3
