# SQL Server

development:
  adapter: sqlserver
  host: .\SQLEXPRESS
  database: ChessOnRails_development
  username: chessonrails
  password: ch3550nrails

test:
  adapter: sqlserver
  host: .\SQLEXPRESS
  database: ChessOnRails_test
  username: chessonrails
  password: ch3550nrails
