# SQL Server

development:
  adapter: mysql
  host: localhost
  database: ChessOnRails_development
  username: chessonrails
  password: ch3550nrails

test:
  adapter: mysql
  host: localhost
  database: ChessOnRails_test
  username: chessonrails
  password: ch3550nrails
