# SQL Server

development:
  adapter: mysql
  host: localhost
  database: ChessOnRails_development
  username: chessonrails
  password: ch3550nrails

test:
  #cant do this yet - but want to !
  #adapter: sqlite3
  #database: ":memory:"
  adapter: mysql
  host: localhost
  database: ChessOnRails_test
  username: chessonrails
  password: ch3550nrails
