# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

development:
  api_key: 69cc9cf788a17cc7b55d29cb41c41bb3
  secret_key: 1db3ad4ff3a616db8912ac3bf7608fda
  canvas_page_name: http://apps.facebook.com/enpassant/
  callback_url: http://enpassant.dyndns.org:3000
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:  
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000